export default {
  colors: [
    {
      id: "brown",
      name: "brown",
      rgbColor: "165,42,42",
      default: true,
      type: "background",
    },
    {
      id: "red",
      name: "red",
      rgbColor: "255,0,0",
      default: true,
      type: "bouncy",
    },
    {
      id: "blue",
      name: "blue",
      rgbColor: "0,0,255",
      default: true,
      type: "temp",
    },
    {
      id: "green",
      name: "green",
      rgbColor: "0,200,0",
      default: true,
      type: "slow",
    },
    { id: "yellow", name: "yellow", rgbColor: "255,255,0", type: undefined },
    {
      id: "purple",
      name: "purple",
      rgbColor: "128,0,128",
      default: true,
      type: "bouncy",
    },
    { id: "orange", name: "orange", rgbColor: "255,165,0", type: undefined },
    { id: "pink", name: "pink", rgbColor: "255,192,203", type: undefined },
    { id: "cyan", name: "cyan", rgbColor: "0,255,255", type: undefined },
    { id: "magenta", name: "magenta", rgbColor: "255,0,255", type: undefined },
    { id: "lime", name: "lime", rgbColor: "0,255,0", type: undefined },
    { id: "teal", name: "teal", rgbColor: "0,128,128", type: undefined },
    { id: "maroon", name: "maroon", rgbColor: "128,0,0", type: undefined },
    { id: "olive", name: "olive", rgbColor: "128,128,0", type: undefined },
    { id: "navy", name: "navy", rgbColor: "0,0,128", type: undefined },
  ],
};
